# Generated by Django 3.0.8 on 2020-07-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200729_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='timestamp',
        ),
    ]
